require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AwsAccountsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # AwsAccount. As you add validations to AwsAccount, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString#{Random.rand}" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AwsAccountsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all aws_accounts as @aws_accounts" do
      aws_account = AwsAccount.create! valid_attributes
      get :index, {}, valid_session
      assigns(:aws_accounts).should eq([aws_account])
    end
  end

  describe "GET show" do
    it "assigns the requested aws_account as @aws_account" do
      aws_account = AwsAccount.create! valid_attributes
      get :show, {:id => aws_account.to_param}, valid_session
      assigns(:aws_account).should eq(aws_account)
    end
  end

  describe "GET new" do
    it "assigns a new aws_account as @aws_account" do
      get :new, {}, valid_session
      assigns(:aws_account).should be_a_new(AwsAccount)
    end
  end

  describe "GET edit" do
    it "assigns the requested aws_account as @aws_account" do
      aws_account = AwsAccount.create! valid_attributes
      get :edit, {:id => aws_account.to_param}, valid_session
      assigns(:aws_account).should eq(aws_account)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AwsAccount" do
        expect {
          post :create, {:aws_account => valid_attributes}, valid_session
        }.to change(AwsAccount, :count).by(1)
      end

      it "assigns a newly created aws_account as @aws_account" do
        post :create, {:aws_account => valid_attributes}, valid_session
        assigns(:aws_account).should be_a(AwsAccount)
        assigns(:aws_account).should be_persisted
      end

      it "redirects to the created aws_account" do
        post :create, {:aws_account => valid_attributes}, valid_session
        response.should redirect_to(AwsAccount.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved aws_account as @aws_account" do
        # Trigger the behavior that occurs when invalid params are submitted
        AwsAccount.any_instance.stub(:save).and_return(false)
        post :create, {:aws_account => { "name" => "invalid value" }}, valid_session
        assigns(:aws_account).should be_a_new(AwsAccount)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AwsAccount.any_instance.stub(:save).and_return(false)
        post :create, {:aws_account => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested aws_account" do
        aws_account = AwsAccount.create! valid_attributes
        # Assuming there are no other aws_accounts in the database, this
        # specifies that the AwsAccount created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AwsAccount.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => aws_account.to_param, :aws_account => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested aws_account as @aws_account" do
        aws_account = AwsAccount.create! valid_attributes
        put :update, {:id => aws_account.to_param, :aws_account => valid_attributes}, valid_session
        assigns(:aws_account).should eq(aws_account)
      end

      it "redirects to the aws_account" do
        aws_account = AwsAccount.create! valid_attributes
        put :update, {:id => aws_account.to_param, :aws_account => valid_attributes}, valid_session
        response.should redirect_to(aws_account)
      end
    end

    describe "with invalid params" do
      it "assigns the aws_account as @aws_account" do
        aws_account = AwsAccount.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AwsAccount.any_instance.stub(:save).and_return(false)
        put :update, {:id => aws_account.to_param, :aws_account => { "name" => "invalid value" }}, valid_session
        assigns(:aws_account).should eq(aws_account)
      end

      it "re-renders the 'edit' template" do
        aws_account = AwsAccount.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AwsAccount.any_instance.stub(:save).and_return(false)
        put :update, {:id => aws_account.to_param, :aws_account => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested aws_account" do
      aws_account = AwsAccount.create! valid_attributes
      expect {
        delete :destroy, {:id => aws_account.to_param}, valid_session
      }.to change(AwsAccount, :count).by(-1)
    end

    it "redirects to the aws_accounts list" do
      aws_account = AwsAccount.create! valid_attributes
      delete :destroy, {:id => aws_account.to_param}, valid_session
      response.should redirect_to(aws_accounts_url)
    end
  end

end
